apiVersion: v1
kind: Service
metadata:
  name: {{ include "apig-dcoos-uportal.fullname" . }}
  labels:
    {{- include "apig-dcoos-uportal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: {{ .Values.clusterIP }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- range .Values.ports }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- end }}
  selector:
    {{- include "apig-dcoos-uportal.selectorLabels" . | nindent 4 }}
