apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ngportal-web-product-r92.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}