apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apig-api-uportal.fullname" . }}
  labels:
    {{- include "apig-api-uportal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "apig-api-uportal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apig-api-uportal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
          - name: global-config
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          {{- toYaml .Values.ports.containerPort | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          {{- range .Values.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
        {{- end }}
        {{- range .Values.cm }}
        - name: {{ .name }}
          configMap:
            - name: {{ .configMap.name }}
        {{- end }}

