apiVersion: v1
kind: Service
metadata:
  name: {{ include "apig-api-uportal.fullname" . }}
  labels:
    {{- include "apig-api-uportal.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.containerPort }}
      protocol: {{ .Values.ports.protocol }}
      name: {{ .Values.ports.http }}
  selector:
    {{- include "apig-api-uportal.selectorLabels" . | nindent 4 }}
