apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otc-service-product.fullname" . }}
  labels:
    {{- include "otc-service-product.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otc-service-product.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otc-service-product.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - envFrom:
          {{ toYaml .Values.envFrom | nindent 10 }}
          name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            {{- toYaml .hostPath | nindent 12 }}
        {{- end }}
        {{- range .Values.cm }}
        - name: {{ .name }}
          configMap:
            {{- toYaml .configMap | nindent 12 }}
        {{- end }}
